from __future__ import annotations

from pathlib import Path

from .storage import hourly_counts, report_from_db


def render_markdown_report(db_path: str | Path, top: int = 10) -> str:
    report = report_from_db(db_path)
    payload = report.to_dict(top=top)
    hourly = hourly_counts(db_path)[-24:]
    lines: list[str] = [
        "# LLM Meter Report",
        "",
        "## Summary",
        "",
        f"- Parsed lines: **{payload['parsed_lines']}**",
        f"- Failed lines: **{payload['failed_lines']}**",
        f"- Time range: `{payload.get('first_seen') or '-'}` → `{payload.get('last_seen') or '-'}`",
        f"- Estimated cost: **${payload['cost']['total_usd']:.6f}**",
        f"- Total tokens: **{payload['tokens']['total']}**",
        "",
        "## Statuses",
        "",
        _table(["Status", "Count"], [(status, count) for status, count in payload["statuses"].items()]),
        "",
        "## Token and cost",
        "",
        _table(
            ["Metric", "Value"],
            [
                ("Prompt tokens", payload["tokens"]["prompt"]),
                ("Completion tokens", payload["tokens"]["completion"]),
                ("Total tokens", payload["tokens"]["total"]),
                ("Estimated cost USD", f"{payload['cost']['total_usd']:.6f}"),
            ],
        ),
        "",
        "## Top models",
        "",
        _table(["Model", "Requests"], list(payload["models"].items())),
        "",
        "## Cost by model",
        "",
        _table(["Model", "Estimated cost USD"], [(model, f"{cost:.6f}") for model, cost in payload["cost"]["by_model"].items()]),
        "",
        "## Top IPs",
        "",
        _table(["IP", "Requests"], list(payload["top_ips"].items())),
        "",
        "## Top paths",
        "",
        _table(["Path", "Requests"], list(payload["paths"].items())),
        "",
        "## Hourly trend",
        "",
        _table(["Hour", "Requests", "2xx", "4xx", "5xx"], [(row["hour"], row["requests"], row["ok"], row["client_errors"], row["server_errors"]) for row in hourly]),
        "",
        "## Signals",
        "",
    ]
    signals = payload.get("signals") or []
    if signals:
        for signal in signals:
            lines.append(f"- **{signal.get('level', '').upper()}** `{signal.get('kind', '')}` — {signal.get('message', '')}")
    else:
        lines.append("- OK no obvious abuse signals")
    lines.extend(["", "---", "Generated by llm-meter.", ""])
    return "\n".join(lines)


def _table(headers: list[str], rows: list[tuple]) -> str:
    if not rows:
        rows = [("-",) * len(headers)]
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    for row in rows:
        padded = list(row) + [""] * (len(headers) - len(row))
        out.append("| " + " | ".join(_cell(value) for value in padded[: len(headers)]) + " |")
    return "\n".join(out)


def _cell(value) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")
